# Generated by Django 5.1 on 2024-10-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.SmallIntegerField(choices=[(1, 'Anagram Hunt'), (2, 'Math Facts')])),
                ('stars', models.SmallIntegerField(choices=[(5, 'Exceptional'), (4, 'Good'), (3, 'Satisfactory'), (2, 'Unsatisfactory'), (1, 'Unacceptable')])),
                ('review', models.TextField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
            ],
        ),
    ]
