# Generated by Django 4.0.5 on 2024-08-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.SmallIntegerField(choices=[(1, 'Exceptional'), (2, 'Good'), (3, 'Satisfactory'), (4, 'Unsatisfactory'), (5, 'Unacceptable')]),
        ),
    ]
