# Generated by Django 5.1 on 2024-09-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_stars'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='one_vote_per_user_per_game',
        ),
        migrations.AlterField(
            model_name='review',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='game',
            field=models.SmallIntegerField(choices=[(1, 'Anagram Hunt'), (2, 'Math Facts')]),
        ),
    ]
