# Generated by Django 5.1 on 2024-10-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
