# Generated by Django 5.1 on 2024-10-03 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnagramHuntScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('max_number', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(5)])),
                ('operation', models.CharField(max_length=30)),
                ('end_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MathFactsScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('max_number', models.IntegerField(default=30, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('operation', models.CharField(max_length=30)),
                ('end_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
