# Generated by Django 5.1 on 2024-10-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagramhuntscores',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mathfactsscores',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
