# Generated by Django 5.1 on 2024-10-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_ascore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ascore',
            name='operation',
            field=models.CharField(default='anagramhunt', max_length=30),
        ),
    ]
