# Generated by Django 5.1 on 2024-10-29 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_mscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.TextField(choices=[('MATH', 'Math Facts'), ('ANAGRAM', 'Anagram Hunt')], default='MATH')),
                ('score', models.IntegerField(default=1)),
                ('max_number', models.IntegerField(default=1)),
                ('operation', models.CharField(max_length=30)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
