# Generated by Django 5.1 on 2024-10-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gamescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('Math Facts', 'MATH'), ('Anagram Hunt', 'ANAGRAM')], default='MATH'),
        ),
    ]
