# Generated by Django 5.1 on 2024-11-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_ascore_user_remove_mathfactsscores_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('Math Facts', 'MATH'), ('Anagram Hunt', 'ANAGRAM')], default='MATH'),
        ),
    ]
