# Generated by Django 5.1 on 2024-11-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_gamescore_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.TextField(choices=[('MATH', 'Math Facts'), ('ANAGRAM', 'Anagram Hunt')], default='MATH'),
        ),
    ]
